theme: jekyll-theme-minimal
title: Xiaohui Liu
description: I work at Physics Department and the Center of Advanced Quantum Studies, Beijing Normal University. My research is focused on particle physics. I am particularly interested in predicting the collider phenomenologies out of the Standard Model first principles.
