theme: jekyll-theme-minimal
title: Xiaohui Liu
description: I work at Physics Department, Beijing Normal University. My research is focused on particle physics. I am particularly interested in predicts the collider phenomenologies out of the first principles.
