theme: jekyll-theme-minimal
title: Xiaohui Liu
description: I am a Professor in the Physics Department and the Center of Advanced Quantum Studies at Beijing Normal University. 
I am also a T.D. Lee Fellow at the Center for High Energy Physics, Peking University. 
My research primarily revolves around particle physics and high-energy nuclear physics, 
with a specific focus on utilizing the first principles of the Standard Model to predict collider phenomenologies.\

We have openings for postdoctoral research fellows in QCD Phenomenology in both nuclear and particle physics. Please contact me if you are interested.   
