theme: jekyll-theme-minimal
title: Liu Group
description: This group is led by Xiaohui Liu, a Professor in the Physics Department at Beijing Normal University, and a T.D. Lee Fellow at the Center for High Energy Physics, Peking University. Our research primarily involves both particle physics and high-energy nuclear physics, with a specific focus on utilizing the first principles of the Standard Model to predict collider phenomenologies.
